apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: fastapiregistrynp00819459.azurecr.io/myapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: GIT_COMMIT_SHA
          value: "abc123"
        - name: SERVICE_PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fastapi

